version: '3.8'

services:
  gdrive-service:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: gdrive-service
    ports:
      - "8095:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:v1Z8z0rR76+JgM3vD/Z47g4n3f1oKjN6e5m4d3c2a1o=
      - QUEUE_CONNECTION=database
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mkas-net

  gdrive-worker:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: gdrive-worker
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - QUEUE_CONNECTION=database
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: php artisan queue:work --tries=3 --delay=3
    networks:
      - mkas-net

networks:
  mkas-net:
    name: mkas-laravel_default
    external: true
