version: "3.8"

services:
  # PHP-FPM Service (Application)
  gdrive-service:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/gdrive-service:latest
    container_name: gdrive-service
    restart: always
    expose:
      - "9000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - QUEUE_CONNECTION=database
    networks:
      - mkas-net
    depends_on:
      - gdrive-db-init

  # Nginx Service (Web Server)
  gdrive-nginx:
    image: nginx:alpine
    container_name: gdrive-nginx
    restart: always
    ports:
      - "8095:80"
    volumes:
      - .:/app:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mkas-net
    depends_on:
      - gdrive-service

  # Queue Worker
  gdrive-worker:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/gdrive-service:latest
    container_name: gdrive-worker
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - QUEUE_CONNECTION=database
    command: php artisan queue:work --tries=3 --delay=3
    networks:
      - mkas-net
    depends_on:
      - gdrive-service

  # Helper service for SQLite (If using SQLite)
  gdrive-db-init:
    image: alpine
    volumes:
      - gdrive-data:/app/database
    command: >
      sh -c "touch /app/database/database.sqlite && chmod 777 /app/database/database.sqlite"

networks:
  mkas-net:
    name: mkas-laravel_default
    external: true

volumes:
  gdrive-data:
